spring.output.ansi.enabled: always
spring:
  application:
    name: zuul-server


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  sensitiveHeaders:
  routes:
    auth:
      path: /auth/**
      serviceId: auth-service
      strip-prefix: true
    users:
      path: /users/**
      serviceId: user-service
      strip-prefix: true
  debug:
    request: true

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka


auth-service:
  ribbon:
    listOfServers: localhost:8090
user-service:
  ribbon:
    listOfServers: localhost:8091
ribbon:
  ReadTimeout: 60000
  eureka:
    enabled: false
  retryable: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ConnectTimeout: 30000

server:
  port: 8080

fs:
  service:
    jwt:
      secret: BFAC53393B0C66AE1B27F4094D00B03F03B19A42271C8112E81FD3E2CC93E954
      rsa-private-key: |
        -----BEGIN PRIVATE KEY-----
        MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAmyhujBh2ZXJHjOG7
        yBI21Sx8IYaEJFchusC8P8Q4djnii3jwXu35BFQnNRIy1RiuN4/GBrZlPXvOB0Zd
        JM5gywIDAQABAkB2v5UL59UFg1c7fbBoSXhp4qgGSJtt7LnF4qiw7Q6BfE7P+A9a
        Bvc2c5V6fNHU/xq1awyCqCnkMjmuOmGqcIPBAiEAyRKIigCHGah3oIsFchb63Dle
        f0LzmVc83GbMgFkm8NsCIQDFiv36yfWPai3Hr+2OcJgXE4ck8qwaFCOowF/552Ca
        0QIgKFFMCYfjjxSFsC5QEDllYcUrGo99MvEYJgWC2fWGZmMCIQC+sQ27qnmBl93Z
        hdqsRcSLgi5TXG8GPaqunAYKF3EKAQIhAKh5YZ/i25WBMaJPMOOQP4aBvC7WJOEV
        PtH+DX36uYrn
        -----END PRIVATE KEY-----
      rsa-public-key: |
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJsobowYdmVyR4zhu8gSNtUsfCGGhCRX
        IbrAvD/EOHY54ot48F7t+QRUJzUSMtUYrjePxga2ZT17zgdGXSTOYMsCAwEAAQ==
        -----END PUBLIC KEY-----
      duration: 900000

logging.level.org.springframework.web.filter:
  CommonsRequestLoggingFilter: DEBUG
